tap "homebrew/bundle"
tap "homebrew/core"
tap "heroku/brew"
brew "mas"
brew "tmux"
brew "heroku"
brew "psql"

# cask
cask "google-chrome"
cask "iterm2"
# 2021/09/06時点で、4.0.0だとエラーが出る
# cask "docker"
cask "macvim"
cask "drawio"
cask "visual-studio-code"
cask "dash"
cask "clipy"
cask "alfred"
cask "typora"
